### ISSUE TITLE
Rendering errors in Ember 3.20

### ISSUE THREAD

**Issue by slovenlyimp** [knownasilya/ember-toggle#147] opened 2020-10-20 21:38 UTC
I upgraded my application from Ember 2.18 to 3.20. Now, when transitioning away from the route that uses `{{x-toggle}}` causes a runtime error.
```
Assertion Failed: You attempted to update `__instance` on 
  `<my-app@component:x-toggle-switch::ember1715>`, 
  but it had already been used previously in the same computation.  
  Attempting to update a value after using it in a computation can cause logical errors, 
  infinite revalidation bugs, and performance issues, and is not supported.
```
Linking the code in `master`, I get the error when entering the route.
```
Error: Assertion Failed: You attempted to update `pan` on `(unknown object)`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

`pan` was first used:

- While rendering:
  application
    my-component
      my-component/child-component
        my-route-1
          my-route-1.my-route-2
            x-toggle
              x-toggle-switch
```

**Comment by knownasilya** [comment] 2020-10-21 00:29
Duplicate of #146

**Closed by knownasilya** 2020-10-21 00:29 UTC

**Comment by slovenlyimp** [comment] 2020-10-21 14:16
For historical purposes, I agree this was a duplicate of https://github.com/knownasilya/ember-toggle/issues/146, I was using ember-cli@3.20, but had accidentally upgraded ember-source to 3.22.
